describe('Pet Applications Component', () => {
  it('Should display the nav bar, title, and applications for a pet', () => {
    cy.visit('http://localhost:3000/pet/1/applications')
      .get('h1')
      .contains('Not Fur-gotten')
      .get('p')
      .contains('Back to Home Page')
      .get('h3')
      .get('.application-container')
      .children()
      .should('have.length', 3)
      .contains('Loki Lucifer')
      .get('p')
      .contains('catsmeow@gmail.com')
      .get('p')
      .contains('Applicant Introduction:')
      .get('p')
      .contains('Lorem ipsum dolor')
  })
})