describe('Pet Applications Component', () => {
  it('Should display the nav bar, title, and applications for a pet', () => {
    cy.visit('http://localhost:3000/pet/1/')
      .get('h1')
      .contains('Not Fur-gotten')
      .get('p')
      .contains('Back to Home Page')
      .get('.about-owner-nav')
      .contains('Read More About the Owner >>')
      .get('.single-pet-name')
      .contains('Stewart')
      .get('.single-pet-age')
      .contains('9 years old')
      .get('.single-pet-gender')
      .contains('Female')
      .get('.single-pet-type')
      .contains('French Bull Dog')
      .get('.single-pet-description')
      .contains("Hi, I'm Stewy!")
      .get('img')
      .should('exist')
      .get('.view-app-button')
      .contains('View Applications')
      .get('.submit-app-button') 
      .contains('Submit Application')
  })
})